version: '3'

networks: 
    laravel:

services:
    lampp-server:
        image: phoenixazrael/xampp
        container_name: lampp-server
        volumes:
            - ./src/:/www/
        ports:
            - 80:80
            - 443:443
            - 3306:3306
            - 21:21
        networks: 
            - laravel
    
    composer:
        image: composer:latest
        volumes:
            - ./src/:/www/
        working_dir: /www/
        networks: 
            - laravel

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - ./src/:/www/
        working_dir: /www/
        entrypoint: ['npm']
        networks: laravel